import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import httpx

if sys.platform == "win32":
    if sys.stdout and hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass
    if sys.stderr and hasattr(sys.stderr, "reconfigure"):
        try:
            sys.stderr.reconfigure(encoding="utf-8")
        except Exception:
            pass

BASE_URL = "http://localhost:8081"
DEFAULT_MODEL_PATH = r"E:\AI\Models\Agentic AI's in CLI\Qwen3-8B\Qwen3-8B-Q4_K_M.gguf"

_client = httpx.Client(base_url=BASE_URL, timeout=120.0)


def strip_thinking(text: str) -> str:
    """Remove <think>...</think> reasoning blocks generated by models like Qwen3."""
    if not text:
        return ""
    if "<think>" in text:
        if "</think>" in text:
            return text.split("</think>")[-1].strip()
        return re.sub(r"<think>.*", "", text, flags=re.DOTALL).strip()
    return text.strip()


def chat(
    messages: list[dict[str, Any]],
    temperature: float = 0.2,
    max_tokens: int = 4096,
    stop: list[str] | None = None,
) -> str:
    """Send a chat completion request to llama-server and return the assistant response text."""
    payload: dict[str, Any] = {
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if stop:
        payload["stop"] = stop

    response = _client.post("/v1/chat/completions", json=payload)
    response.raise_for_status()
    data = response.json()
    content = str(data["choices"][0]["message"]["content"])
    return strip_thinking(content)


def count_tokens(text: str) -> int:
    """Estimate token count using a simple chars/4 heuristic."""
    if not text:
        return 0
    return len(text) // 4


def health_check() -> bool:
    """Return True if llama-server is responding on the configured port."""
    try:
        response = _client.get("/health")
        return response.status_code == 200
    except (httpx.ConnectError, httpx.TimeoutException):
        return False


def find_llama_server() -> str:
    """Find llama-server binary on PATH or in common installation paths."""
    env_path = os.environ.get("LLAMA_SERVER_PATH")
    if env_path and Path(env_path).is_file():
        return env_path

    on_path = shutil.which("llama-server") or shutil.which("llama-server.exe")
    if on_path:
        return on_path

    candidates = [
        Path.home() / "AppData" / "Local" / "Programs" / "Ollama" / "lib" / "ollama" / "llama-server.exe",
        Path.home() / "AppData" / "Local" / "Programs" / "Ollama" / "llama-server.exe",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return str(candidate)

    return "llama-server"


def ensure_server(
    model_path: str = DEFAULT_MODEL_PATH,
    port: int = 8081,
    ctx_size: int = 8192,
    server_bin: str | None = None,
) -> subprocess.Popen | None:
    """Launch llama-server if not already running. Return Popen handle or None if running."""
    if health_check():
        return None

    binary = server_bin or find_llama_server()
    cmd = [
        binary,
        "-m",
        model_path,
        "--port",
        str(port),
        "-c",
        str(ctx_size),
        "-ngl",
        "99",
        "--chat-template",
        "chatml",
    ]
    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError as e:
        raise FileNotFoundError(
            f"Could not find llama-server executable '{binary}'. "
            "Please ensure llama-server is on PATH or set LLAMA_SERVER_PATH environment variable."
        ) from e

    start_time = time.time()
    while time.time() - start_time < 30.0:
        if health_check():
            return proc
        time.sleep(0.5)

    proc.kill()
    raise RuntimeError(f"llama-server failed to start within 30s: {' '.join(cmd)}")


